npm i eslint -D
npm i eslint-config-airbnb -D
npm i eslint-config-prettier -D
npm i eslint-plugin-import -D
npm i eslint-plugin-jsx-a11y -D
npm i eslint-plugin-prettier -D
npm i eslint-plugin-react -D
npm i eslint-plugin-react-hooks -D
npm i @typescript-eslint/eslint-plugin -D
npm i @typescript-eslint/parsers -D
npm i vite-tsconfig-paths -D